### ISSUE TITLE
@OnKey annotation doesnt respect setting additional keys to false

### ISSUE THREAD

**Issue by AlexanderPineiro** [fujaba/fulibFx#101]
**Describe the bug**
When using two functions annotated with @OnKey(code = KeyCode.ENTER, shift = false) and @OnKey(code = KeyCode.ENTER, shift = true)  respectively the first gets called even when shift is pressed

**To Reproduce**
1. Write 2 functions and annotate them as mentioned above
2. Press shift enter
3. Both functions get called because setting shift=false is not respected

**Expected behavior**
Only one functions gets called depending on whether shift is pressed or not. 

**Desktop (please complete the following information):**
 - OS: 6.9.1.arch1-1

**Comment by LeStegii** [comment]
This actually works as intended. 

As written in the [javadocs](https://github.com/fujaba/fulibFx/blob/a14b9bf84cb54e1086ceb04f67044aef798547db/framework/src/main/java/org/fulib/fx/annotation/event/OnKey.java#L42), `shift` specifies whether the shift key has to be pressed.
Setting `shift = false` only makes it so that you **don't have to** press shift.
This behavior is used because it is more likely that pressing "shift" is either ignored or required, rather than requiring "shift" not to be pressed.

In order to check if shift is not pressed during the event, add a `KeyEvent` as a method parameter and check manually.

I see why this is confusing though, so maybe renaming `shift`to `requireShift` could help. If you have any suggestions on this let us know.

**Comment by Clashsoft** [comment]
Please suggest a possible solution. There is no way to tell the difference in the program between these

```
@OnKey() // shift() default false
void foo()

@OnKey(shift = false)
void bar()

getMethod("foo").getAnnotation(OnKey.class).shift() // == false
getMethod("bar").getAnnotation(OnKey.class).shift() // == false
```

We already thought about a tristate value (e.g. enum), but that would be a breaking change and imo cumbersome.

```java
enum State { IGNORED, REQUIRED, PROHIBITED }

@OnKey(shift = State.REQUIRED)
@OnKey(shift = State.PROHIBITED)
```
